export const data = [
  {
    id: 1,
    name: 'Coconut Oil',
    thumbUrl: '/assets/prod1',
    quantity: 'Clay.Batz43@yahoo.com',
    price: 'Kshs 250',
  },
  {
    id: 2,
    name: 'Coconut Oil',
    thumbUrl: src = '',
    quantity: 'Clay.Batz43@yahoo.com',
    price: 'Kshs 250',
  },
  {
    id: 3,
    name: 'Coconut Oil',
    thumbUrl: src = '',
    quantity: 'Clay.Batz43@yahoo.com',
    price: 'Kshs 250',
  },
  {
    id: 4,
    name: 'Coconut Oil',
    thumbUrl: src = '',
    quantity: 'Clay.Batz43@yahoo.com',
    price: 'Kshs 250',
  },
  {
    id: 5,
    name: 'Coconut Oil',
    thumbUrl: src = '',
    quantity: 'Clay.Batz43@yahoo.com',
    price: 'Kshs 250',
  },
  {
    id: 6,
    name: 'Coconut Oil',
    thumbUrl: src = '',
    quantity: 'Clay.Batz43@yahoo.com',
    price: 'Kshs 250',
  },
  {
    id: 7,
    name: 'Coconut Oil',
    thumbUrl: src = '',
    quantity: 'Clay.Batz43@yahoo.com',
    price: 'Kshs 250',
  },
  {
    id: 8,
    name: 'Coconut Oil',
    thumbUrl: src = '',
    quantity: 'Clay.Batz43@yahoo.com',
    price: 'Kshs 250',
  },
  {
    id: 9,
    name: 'Coconut Oil',
    thumbUrl: src = '',
    quantity: 'Clay.Batz43@yahoo.com',
    price: 'Kshs 250',
  },
  {
    id: 10,
    name: 'Coconut Oil',
    thumbUrl: src = '',
    quantity: 'Clay.Batz43@yahoo.com',
    price: 'Kshs 250',
  },
  {
    id: 11,
    name: 'Coconut Oil',
    thumbUrl: src = '',
    quantity: 'Clay.Batz43@yahoo.com',
    price: 'Kshs 250',
  },
  {
    id: 12,
    name: 'Coconut Oil',
    thumbUrl: src = '',
    quantity: 'Clay.Batz43@yahoo.com',
    price: 'Kshs 250',
  },
  {
    id: 13,
    name: 'Coconut Oil',
    thumbUrl: src = '',
    quantity: 'Clay.Batz43@yahoo.com',
    price: 'Kshs 250',
  },
  {
    id: 14,
    name: 'Coconut Oil',
    thumbUrl: src = '',
    quantity: 'Clay.Batz43@yahoo.com',
    price: 'Kshs 250',
  },
  {
    id: 15,
    name: 'Coconut Oil',
    thumbUrl: src = '',
    quantity: 'Clay.Batz43@yahoo.com',
    price: 'Kshs 250',
  },
  {
    id: 16,
    name: 'Coconut Oil',
    thumbUrl: src = '',
    quantity: 'Clay.Batz43@yahoo.com',
    price: 'Kshs 250',
  },
  {
    id: 17,
    name: 'Coconut Oil',
    thumbUrl: src = '',
    quantity: 'Clay.Batz43@yahoo.com',
    price: 'Kshs 250',
  },
  {
    id: 18,
    name: 'Coconut Oil',
    thumbUrl: src = '',
    quantity: 'Clay.Batz43@yahoo.com',
    price: 'Kshs 250',
  },
  {
    id: 19,
    name: 'Coconut Oil',
    thumbUrl: src = '',
    quantity: 'Clay.Batz43@yahoo.com',
    price: 'Kshs 250',
  },
  {
    id: 20,
    name: 'Coconut Oil',
    thumbUrl: src = '',
    quantity: 'Clay.Batz43@yahoo.com',
    price: 'Kshs 250',
  },
  {
    name: 'Coconut Oil',
    thumbUrl: src = '',
    quantity: 'Clay.Batz43@yahoo.com',
    price: 'Kshs 250',
  },
  {
    id: 22,
    name: 'Coconut Oil',
    thumbUrl: src = '',
    quantity: 'Clay.Batz43@yahoo.com',
    price: 'Kshs 250',
  },
];
